/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreLoginRouteImport } from './routes/store-login'
import { Route as SiteRouteImport } from './routes/site'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedStocktakeRouteImport } from './routes/_authenticated/stocktake'
import { Route as AuthenticatedStockLogRouteImport } from './routes/_authenticated/stock-log'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSpecialistRouteImport } from './routes/_authenticated/specialist'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated/financials'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedCashRouteImport } from './routes/_authenticated/cash'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBookingSettingsRouteImport } from './routes/_authenticated/booking-settings'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedAccountingIndexRouteImport } from './routes/_authenticated/accounting.index'
import { Route as AuthenticatedAccountingVatRouteImport } from './routes/_authenticated/accounting.vat'
import { Route as AuthenticatedAccountingTrialBalanceRouteImport } from './routes/_authenticated/accounting.trial-balance'
import { Route as AuthenticatedAccountingJournalRouteImport } from './routes/_authenticated/accounting.journal'
import { Route as AuthenticatedAccountingFinancialsRouteImport } from './routes/_authenticated/accounting.financials'
import { Route as AuthenticatedAccountingEinvoiceRouteImport } from './routes/_authenticated/accounting.einvoice'
import { Route as AuthenticatedAccountingCreditNotesRouteImport } from './routes/_authenticated/accounting.credit-notes'
import { Route as AuthenticatedAccountingClosingRouteImport } from './routes/_authenticated/accounting.closing'
import { Route as AuthenticatedAccountingAssetsRouteImport } from './routes/_authenticated/accounting.assets'
import { Route as AuthenticatedAccountingAccountsRouteImport } from './routes/_authenticated/accounting.accounts'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const StoreLoginRoute = StoreLoginRouteImport.update({
  id: '/store-login',
  path: '/store-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStocktakeRoute = AuthenticatedStocktakeRouteImport.update({
  id: '/stocktake',
  path: '/stocktake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockLogRoute = AuthenticatedStockLogRouteImport.update({
  id: '/stock-log',
  path: '/stock-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpecialistRoute = AuthenticatedSpecialistRouteImport.update({
  id: '/specialist',
  path: '/specialist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashRoute = AuthenticatedCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingSettingsRoute =
  AuthenticatedBookingSettingsRouteImport.update({
    id: '/booking-settings',
    path: '/booking-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingIndexRoute =
  AuthenticatedAccountingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingVatRoute =
  AuthenticatedAccountingVatRouteImport.update({
    id: '/vat',
    path: '/vat',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingTrialBalanceRoute =
  AuthenticatedAccountingTrialBalanceRouteImport.update({
    id: '/trial-balance',
    path: '/trial-balance',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingJournalRoute =
  AuthenticatedAccountingJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingFinancialsRoute =
  AuthenticatedAccountingFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingEinvoiceRoute =
  AuthenticatedAccountingEinvoiceRouteImport.update({
    id: '/einvoice',
    path: '/einvoice',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingCreditNotesRoute =
  AuthenticatedAccountingCreditNotesRouteImport.update({
    id: '/credit-notes',
    path: '/credit-notes',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingClosingRoute =
  AuthenticatedAccountingClosingRouteImport.update({
    id: '/closing',
    path: '/closing',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingAssetsRoute =
  AuthenticatedAccountingAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingAccountsRoute =
  AuthenticatedAccountingAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/no-access': typeof NoAccessRoute
  '/site': typeof SiteRoute
  '/store-login': typeof StoreLoginRoute
  '/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/accounts': typeof AuthenticatedAccountsRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/booking-settings': typeof AuthenticatedBookingSettingsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cash': typeof AuthenticatedCashRoute
  '/client': typeof AuthenticatedClientRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/pos': typeof AuthenticatedPosRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/specialist': typeof AuthenticatedSpecialistRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stock-log': typeof AuthenticatedStockLogRoute
  '/stocktake': typeof AuthenticatedStocktakeRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/users': typeof AuthenticatedUsersRoute
  '/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/accounting/assets': typeof AuthenticatedAccountingAssetsRoute
  '/accounting/closing': typeof AuthenticatedAccountingClosingRoute
  '/accounting/credit-notes': typeof AuthenticatedAccountingCreditNotesRoute
  '/accounting/einvoice': typeof AuthenticatedAccountingEinvoiceRoute
  '/accounting/financials': typeof AuthenticatedAccountingFinancialsRoute
  '/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/accounting/vat': typeof AuthenticatedAccountingVatRoute
  '/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/no-access': typeof NoAccessRoute
  '/site': typeof SiteRoute
  '/store-login': typeof StoreLoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/booking-settings': typeof AuthenticatedBookingSettingsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/cash': typeof AuthenticatedCashRoute
  '/client': typeof AuthenticatedClientRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/pos': typeof AuthenticatedPosRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/specialist': typeof AuthenticatedSpecialistRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stock-log': typeof AuthenticatedStockLogRoute
  '/stocktake': typeof AuthenticatedStocktakeRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/users': typeof AuthenticatedUsersRoute
  '/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/accounting/assets': typeof AuthenticatedAccountingAssetsRoute
  '/accounting/closing': typeof AuthenticatedAccountingClosingRoute
  '/accounting/credit-notes': typeof AuthenticatedAccountingCreditNotesRoute
  '/accounting/einvoice': typeof AuthenticatedAccountingEinvoiceRoute
  '/accounting/financials': typeof AuthenticatedAccountingFinancialsRoute
  '/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/accounting/vat': typeof AuthenticatedAccountingVatRoute
  '/accounting': typeof AuthenticatedAccountingIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/no-access': typeof NoAccessRoute
  '/site': typeof SiteRoute
  '/store-login': typeof StoreLoginRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/booking-settings': typeof AuthenticatedBookingSettingsRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/cash': typeof AuthenticatedCashRoute
  '/_authenticated/client': typeof AuthenticatedClientRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/specialist': typeof AuthenticatedSpecialistRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/stock-log': typeof AuthenticatedStockLogRoute
  '/_authenticated/stocktake': typeof AuthenticatedStocktakeRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/_authenticated/accounting/assets': typeof AuthenticatedAccountingAssetsRoute
  '/_authenticated/accounting/closing': typeof AuthenticatedAccountingClosingRoute
  '/_authenticated/accounting/credit-notes': typeof AuthenticatedAccountingCreditNotesRoute
  '/_authenticated/accounting/einvoice': typeof AuthenticatedAccountingEinvoiceRoute
  '/_authenticated/accounting/financials': typeof AuthenticatedAccountingFinancialsRoute
  '/_authenticated/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/_authenticated/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/_authenticated/accounting/vat': typeof AuthenticatedAccountingVatRoute
  '/_authenticated/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/no-access'
    | '/site'
    | '/store-login'
    | '/accounting'
    | '/accounts'
    | '/activity-log'
    | '/assets'
    | '/attendance'
    | '/booking-settings'
    | '/bookings'
    | '/branches'
    | '/calendar'
    | '/cash'
    | '/client'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/financials'
    | '/inventory'
    | '/invoices'
    | '/onboarding'
    | '/payroll'
    | '/platform'
    | '/pos'
    | '/reports'
    | '/services'
    | '/settings'
    | '/specialist'
    | '/staff'
    | '/stock-log'
    | '/stocktake'
    | '/subscription'
    | '/users'
    | '/accounting/accounts'
    | '/accounting/assets'
    | '/accounting/closing'
    | '/accounting/credit-notes'
    | '/accounting/einvoice'
    | '/accounting/financials'
    | '/accounting/journal'
    | '/accounting/trial-balance'
    | '/accounting/vat'
    | '/accounting/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/no-access'
    | '/site'
    | '/store-login'
    | '/accounts'
    | '/activity-log'
    | '/assets'
    | '/attendance'
    | '/booking-settings'
    | '/bookings'
    | '/branches'
    | '/calendar'
    | '/cash'
    | '/client'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/financials'
    | '/inventory'
    | '/invoices'
    | '/onboarding'
    | '/payroll'
    | '/platform'
    | '/pos'
    | '/reports'
    | '/services'
    | '/settings'
    | '/specialist'
    | '/staff'
    | '/stock-log'
    | '/stocktake'
    | '/subscription'
    | '/users'
    | '/accounting/accounts'
    | '/accounting/assets'
    | '/accounting/closing'
    | '/accounting/credit-notes'
    | '/accounting/einvoice'
    | '/accounting/financials'
    | '/accounting/journal'
    | '/accounting/trial-balance'
    | '/accounting/vat'
    | '/accounting'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/no-access'
    | '/site'
    | '/store-login'
    | '/_authenticated/accounting'
    | '/_authenticated/accounts'
    | '/_authenticated/activity-log'
    | '/_authenticated/assets'
    | '/_authenticated/attendance'
    | '/_authenticated/booking-settings'
    | '/_authenticated/bookings'
    | '/_authenticated/branches'
    | '/_authenticated/calendar'
    | '/_authenticated/cash'
    | '/_authenticated/client'
    | '/_authenticated/coupons'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/financials'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/onboarding'
    | '/_authenticated/payroll'
    | '/_authenticated/platform'
    | '/_authenticated/pos'
    | '/_authenticated/reports'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/specialist'
    | '/_authenticated/staff'
    | '/_authenticated/stock-log'
    | '/_authenticated/stocktake'
    | '/_authenticated/subscription'
    | '/_authenticated/users'
    | '/_authenticated/accounting/accounts'
    | '/_authenticated/accounting/assets'
    | '/_authenticated/accounting/closing'
    | '/_authenticated/accounting/credit-notes'
    | '/_authenticated/accounting/einvoice'
    | '/_authenticated/accounting/financials'
    | '/_authenticated/accounting/journal'
    | '/_authenticated/accounting/trial-balance'
    | '/_authenticated/accounting/vat'
    | '/_authenticated/accounting/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NoAccessRoute: typeof NoAccessRoute
  SiteRoute: typeof SiteRoute
  StoreLoginRoute: typeof StoreLoginRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-login': {
      id: '/store-login'
      path: '/store-login'
      fullPath: '/store-login'
      preLoaderRoute: typeof StoreLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stocktake': {
      id: '/_authenticated/stocktake'
      path: '/stocktake'
      fullPath: '/stocktake'
      preLoaderRoute: typeof AuthenticatedStocktakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-log': {
      id: '/_authenticated/stock-log'
      path: '/stock-log'
      fullPath: '/stock-log'
      preLoaderRoute: typeof AuthenticatedStockLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/specialist': {
      id: '/_authenticated/specialist'
      path: '/specialist'
      fullPath: '/specialist'
      preLoaderRoute: typeof AuthenticatedSpecialistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash': {
      id: '/_authenticated/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof AuthenticatedCashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking-settings': {
      id: '/_authenticated/booking-settings'
      path: '/booking-settings'
      fullPath: '/booking-settings'
      preLoaderRoute: typeof AuthenticatedBookingSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/': {
      id: '/_authenticated/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthenticatedAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/vat': {
      id: '/_authenticated/accounting/vat'
      path: '/vat'
      fullPath: '/accounting/vat'
      preLoaderRoute: typeof AuthenticatedAccountingVatRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/trial-balance': {
      id: '/_authenticated/accounting/trial-balance'
      path: '/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AuthenticatedAccountingTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/journal': {
      id: '/_authenticated/accounting/journal'
      path: '/journal'
      fullPath: '/accounting/journal'
      preLoaderRoute: typeof AuthenticatedAccountingJournalRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/financials': {
      id: '/_authenticated/accounting/financials'
      path: '/financials'
      fullPath: '/accounting/financials'
      preLoaderRoute: typeof AuthenticatedAccountingFinancialsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/einvoice': {
      id: '/_authenticated/accounting/einvoice'
      path: '/einvoice'
      fullPath: '/accounting/einvoice'
      preLoaderRoute: typeof AuthenticatedAccountingEinvoiceRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/credit-notes': {
      id: '/_authenticated/accounting/credit-notes'
      path: '/credit-notes'
      fullPath: '/accounting/credit-notes'
      preLoaderRoute: typeof AuthenticatedAccountingCreditNotesRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/closing': {
      id: '/_authenticated/accounting/closing'
      path: '/closing'
      fullPath: '/accounting/closing'
      preLoaderRoute: typeof AuthenticatedAccountingClosingRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/assets': {
      id: '/_authenticated/accounting/assets'
      path: '/assets'
      fullPath: '/accounting/assets'
      preLoaderRoute: typeof AuthenticatedAccountingAssetsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/accounts': {
      id: '/_authenticated/accounting/accounts'
      path: '/accounts'
      fullPath: '/accounting/accounts'
      preLoaderRoute: typeof AuthenticatedAccountingAccountsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountingRouteChildren {
  AuthenticatedAccountingAccountsRoute: typeof AuthenticatedAccountingAccountsRoute
  AuthenticatedAccountingAssetsRoute: typeof AuthenticatedAccountingAssetsRoute
  AuthenticatedAccountingClosingRoute: typeof AuthenticatedAccountingClosingRoute
  AuthenticatedAccountingCreditNotesRoute: typeof AuthenticatedAccountingCreditNotesRoute
  AuthenticatedAccountingEinvoiceRoute: typeof AuthenticatedAccountingEinvoiceRoute
  AuthenticatedAccountingFinancialsRoute: typeof AuthenticatedAccountingFinancialsRoute
  AuthenticatedAccountingJournalRoute: typeof AuthenticatedAccountingJournalRoute
  AuthenticatedAccountingTrialBalanceRoute: typeof AuthenticatedAccountingTrialBalanceRoute
  AuthenticatedAccountingVatRoute: typeof AuthenticatedAccountingVatRoute
  AuthenticatedAccountingIndexRoute: typeof AuthenticatedAccountingIndexRoute
}

const AuthenticatedAccountingRouteChildren: AuthenticatedAccountingRouteChildren =
  {
    AuthenticatedAccountingAccountsRoute: AuthenticatedAccountingAccountsRoute,
    AuthenticatedAccountingAssetsRoute: AuthenticatedAccountingAssetsRoute,
    AuthenticatedAccountingClosingRoute: AuthenticatedAccountingClosingRoute,
    AuthenticatedAccountingCreditNotesRoute:
      AuthenticatedAccountingCreditNotesRoute,
    AuthenticatedAccountingEinvoiceRoute: AuthenticatedAccountingEinvoiceRoute,
    AuthenticatedAccountingFinancialsRoute:
      AuthenticatedAccountingFinancialsRoute,
    AuthenticatedAccountingJournalRoute: AuthenticatedAccountingJournalRoute,
    AuthenticatedAccountingTrialBalanceRoute:
      AuthenticatedAccountingTrialBalanceRoute,
    AuthenticatedAccountingVatRoute: AuthenticatedAccountingVatRoute,
    AuthenticatedAccountingIndexRoute: AuthenticatedAccountingIndexRoute,
  }

const AuthenticatedAccountingRouteWithChildren =
  AuthenticatedAccountingRoute._addFileChildren(
    AuthenticatedAccountingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRouteWithChildren
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBookingSettingsRoute: typeof AuthenticatedBookingSettingsRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCashRoute: typeof AuthenticatedCashRoute
  AuthenticatedClientRoute: typeof AuthenticatedClientRoute
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpecialistRoute: typeof AuthenticatedSpecialistRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStockLogRoute: typeof AuthenticatedStockLogRoute
  AuthenticatedStocktakeRoute: typeof AuthenticatedStocktakeRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRouteWithChildren,
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBookingSettingsRoute: AuthenticatedBookingSettingsRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCashRoute: AuthenticatedCashRoute,
  AuthenticatedClientRoute: AuthenticatedClientRoute,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpecialistRoute: AuthenticatedSpecialistRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStockLogRoute: AuthenticatedStockLogRoute,
  AuthenticatedStocktakeRoute: AuthenticatedStocktakeRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NoAccessRoute: NoAccessRoute,
  SiteRoute: SiteRoute,
  StoreLoginRoute: StoreLoginRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
