/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/site'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSpecialistRouteImport } from './routes/_authenticated/specialist'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBookingSettingsRouteImport } from './routes/_authenticated/booking-settings'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'

const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpecialistRoute = AuthenticatedSpecialistRouteImport.update({
  id: '/specialist',
  path: '/specialist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingSettingsRoute =
  AuthenticatedBookingSettingsRouteImport.update({
    id: '/booking-settings',
    path: '/booking-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/site': typeof SiteRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/booking-settings': typeof AuthenticatedBookingSettingsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/client': typeof AuthenticatedClientRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/specialist': typeof AuthenticatedSpecialistRoute
  '/staff': typeof AuthenticatedStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/site': typeof SiteRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/booking-settings': typeof AuthenticatedBookingSettingsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/client': typeof AuthenticatedClientRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/specialist': typeof AuthenticatedSpecialistRoute
  '/staff': typeof AuthenticatedStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/site': typeof SiteRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/booking-settings': typeof AuthenticatedBookingSettingsRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/client': typeof AuthenticatedClientRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/specialist': typeof AuthenticatedSpecialistRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/site'
    | '/attendance'
    | '/booking-settings'
    | '/bookings'
    | '/calendar'
    | '/client'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/invoices'
    | '/payroll'
    | '/services'
    | '/settings'
    | '/specialist'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/site'
    | '/attendance'
    | '/booking-settings'
    | '/bookings'
    | '/calendar'
    | '/client'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/invoices'
    | '/payroll'
    | '/services'
    | '/settings'
    | '/specialist'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/site'
    | '/_authenticated/attendance'
    | '/_authenticated/booking-settings'
    | '/_authenticated/bookings'
    | '/_authenticated/calendar'
    | '/_authenticated/client'
    | '/_authenticated/coupons'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/payroll'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/specialist'
    | '/_authenticated/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SiteRoute: typeof SiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/specialist': {
      id: '/_authenticated/specialist'
      path: '/specialist'
      fullPath: '/specialist'
      preLoaderRoute: typeof AuthenticatedSpecialistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking-settings': {
      id: '/_authenticated/booking-settings'
      path: '/booking-settings'
      fullPath: '/booking-settings'
      preLoaderRoute: typeof AuthenticatedBookingSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBookingSettingsRoute: typeof AuthenticatedBookingSettingsRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClientRoute: typeof AuthenticatedClientRoute
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSpecialistRoute: typeof AuthenticatedSpecialistRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBookingSettingsRoute: AuthenticatedBookingSettingsRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClientRoute: AuthenticatedClientRoute,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSpecialistRoute: AuthenticatedSpecialistRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SiteRoute: SiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
